version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=your_database_name
    # restart: always
volumes:
  mongo-data: